### ISSUE TITLE
Is it safe to using mutex between splin_lock and spin_unlock?

### ISSUE THREAD

**Issue by panda-mute** [mrvltest/mwlwifi-8997#1]
The function **mwl_mac80211_sta_remove()** in mac80211.c use splin_lock to protect
**mwl_fwcmd_del_sta_streams()**. 

And **mwl_fwcmd_del_sta_streams()** will call **mwl_fwcmd_destroy_ba()** which using mutex.

**Comment by mrvltest** [comment]
Fixed. Please help to compile and verify it. Thanks.

**Comment by panda-mute** [comment]
Sure
